-- =============================================================
-- Project Feasibility Schema - Oracle
-- =============================================================

CREATE TABLE projects (
  id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(255 CHAR) NOT NULL UNIQUE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE feasibility_runs (
  id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  project_id  NUMBER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  version     NUMBER,
  status      VARCHAR2(20 CHAR) DEFAULT 'draft' NOT NULL CHECK (status IN ('draft', 'frozen')),
  payload     CLOB NOT NULL CHECK (payload IS JSON),
  metrics     CLOB NOT NULL CHECK (metrics IS JSON),
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  frozen_at   TIMESTAMP WITH TIME ZONE,
  CONSTRAINT uq_feasibility_runs_project_version UNIQUE (project_id, version)
);

CREATE TABLE feasibility_archive (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  original_run_id NUMBER NOT NULL,
  project_id      NUMBER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  version         NUMBER NOT NULL,
  payload         CLOB NOT NULL CHECK (payload IS JSON),
  metrics         CLOB NOT NULL CHECK (metrics IS JSON),
  frozen_at       TIMESTAMP WITH TIME ZONE,
  archived_at     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_feasibility_runs_project_version
  ON feasibility_runs (project_id, version DESC);

CREATE INDEX idx_feasibility_archive_project
  ON feasibility_archive (project_id, version DESC);

CREATE UNIQUE INDEX uq_feasibility_runs_one_draft_per_project
  ON feasibility_runs (CASE WHEN status = 'draft' THEN project_id END);

CREATE TABLE feasibility_reporting_current (
  run_id               NUMBER PRIMARY KEY REFERENCES feasibility_runs(id) ON DELETE CASCADE,
  project_id           NUMBER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  version              NUMBER,
  status               VARCHAR2(20 CHAR) NOT NULL CHECK (status IN ('draft', 'frozen')),
  created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
  frozen_at            TIMESTAMP WITH TIME ZONE,
  project_name         VARCHAR2(255 CHAR) NOT NULL,
  land_area            NUMBER,
  land_cost            NUMBER,
  gfa                  NUMBER,
  nsa_resi             NUMBER,
  nsa_retail           NUMBER,
  bua_resi             NUMBER,
  bua_retail           NUMBER,
  units_resi           NUMBER,
  units_retail         NUMBER,
  resi_psf             NUMBER,
  retail_psf           NUMBER,
  cc_psf               NUMBER,
  soft_pct             NUMBER,
  stat_pct             NUMBER,
  cont_pct             NUMBER,
  dev_mgmt_pct         NUMBER,
  cof_pct              NUMBER,
  sales_exp_pct        NUMBER,
  mkt_pct              NUMBER,
  area_land_area       NUMBER NOT NULL,
  area_gfa             NUMBER NOT NULL,
  area_nsa_resi        NUMBER NOT NULL,
  area_nsa_retail      NUMBER NOT NULL,
  area_nsa_total       NUMBER NOT NULL,
  area_bua_resi        NUMBER NOT NULL,
  area_bua_retail      NUMBER NOT NULL,
  area_bua_total       NUMBER NOT NULL,
  area_units_resi      NUMBER NOT NULL,
  area_units_retail    NUMBER NOT NULL,
  area_units_total     NUMBER NOT NULL,
  area_efficiency_pct  NUMBER NOT NULL,
  revenue_resi         NUMBER NOT NULL,
  revenue_retail       NUMBER NOT NULL,
  revenue_total        NUMBER NOT NULL,
  cost_land_resi       NUMBER NOT NULL,
  cost_land_retail     NUMBER NOT NULL,
  cost_land            NUMBER NOT NULL,
  cost_cc_resi         NUMBER NOT NULL,
  cost_cc_retail       NUMBER NOT NULL,
  cost_construction    NUMBER NOT NULL,
  cost_soft_resi       NUMBER NOT NULL,
  cost_soft_retail     NUMBER NOT NULL,
  cost_soft            NUMBER NOT NULL,
  cost_stat_resi       NUMBER NOT NULL,
  cost_stat_retail     NUMBER NOT NULL,
  cost_statutory       NUMBER NOT NULL,
  cost_cont_resi       NUMBER NOT NULL,
  cost_cont_retail     NUMBER NOT NULL,
  cost_contingency     NUMBER NOT NULL,
  cost_dev_resi        NUMBER NOT NULL,
  cost_dev_retail      NUMBER NOT NULL,
  cost_dev_mgmt        NUMBER NOT NULL,
  cost_cof_resi        NUMBER NOT NULL,
  cost_cof_retail      NUMBER NOT NULL,
  cost_cof             NUMBER NOT NULL,
  cost_se_resi         NUMBER NOT NULL,
  cost_se_retail       NUMBER NOT NULL,
  cost_sales_expense   NUMBER NOT NULL,
  cost_mk_resi         NUMBER NOT NULL,
  cost_mk_retail       NUMBER NOT NULL,
  cost_marketing       NUMBER NOT NULL,
  cost_resi            NUMBER NOT NULL,
  cost_retail          NUMBER NOT NULL,
  cost_total           NUMBER NOT NULL,
  profit_np_resi       NUMBER NOT NULL,
  profit_np_retail     NUMBER NOT NULL,
  profit_net_profit    NUMBER NOT NULL,
  profit_margin_resi   NUMBER NOT NULL,
  profit_margin_retail NUMBER NOT NULL,
  profit_margin_pct    NUMBER NOT NULL,
  kpi_total_revenue    NUMBER NOT NULL,
  kpi_total_cost       NUMBER NOT NULL,
  kpi_net_profit       NUMBER NOT NULL,
  kpi_margin_pct       NUMBER NOT NULL,
  kpi_total_units      NUMBER NOT NULL
);

CREATE INDEX idx_feasibility_reporting_current_project
  ON feasibility_reporting_current (project_id, updated_at DESC);

CREATE TABLE feasibility_reporting_current_partners (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  run_id        NUMBER NOT NULL REFERENCES feasibility_reporting_current(run_id) ON DELETE CASCADE,
  partner_order NUMBER NOT NULL,
  partner_name  VARCHAR2(255 CHAR) NOT NULL,
  share_pct     NUMBER NOT NULL,
  profit_share  NUMBER NOT NULL
);

CREATE INDEX idx_feasibility_reporting_current_partners_run
  ON feasibility_reporting_current_partners (run_id, partner_order);

CREATE TABLE feasibility_reporting_archive (
  archive_id           NUMBER PRIMARY KEY REFERENCES feasibility_archive(id) ON DELETE CASCADE,
  original_run_id      NUMBER NOT NULL,
  project_id           NUMBER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  version              NUMBER NOT NULL,
  frozen_at            TIMESTAMP WITH TIME ZONE,
  archived_at          TIMESTAMP WITH TIME ZONE NOT NULL,
  project_name         VARCHAR2(255 CHAR) NOT NULL,
  land_area            NUMBER,
  land_cost            NUMBER,
  gfa                  NUMBER,
  nsa_resi             NUMBER,
  nsa_retail           NUMBER,
  bua_resi             NUMBER,
  bua_retail           NUMBER,
  units_resi           NUMBER,
  units_retail         NUMBER,
  resi_psf             NUMBER,
  retail_psf           NUMBER,
  cc_psf               NUMBER,
  soft_pct             NUMBER,
  stat_pct             NUMBER,
  cont_pct             NUMBER,
  dev_mgmt_pct         NUMBER,
  cof_pct              NUMBER,
  sales_exp_pct        NUMBER,
  mkt_pct              NUMBER,
  area_land_area       NUMBER NOT NULL,
  area_gfa             NUMBER NOT NULL,
  area_nsa_resi        NUMBER NOT NULL,
  area_nsa_retail      NUMBER NOT NULL,
  area_nsa_total       NUMBER NOT NULL,
  area_bua_resi        NUMBER NOT NULL,
  area_bua_retail      NUMBER NOT NULL,
  area_bua_total       NUMBER NOT NULL,
  area_units_resi      NUMBER NOT NULL,
  area_units_retail    NUMBER NOT NULL,
  area_units_total     NUMBER NOT NULL,
  area_efficiency_pct  NUMBER NOT NULL,
  revenue_resi         NUMBER NOT NULL,
  revenue_retail       NUMBER NOT NULL,
  revenue_total        NUMBER NOT NULL,
  cost_land_resi       NUMBER NOT NULL,
  cost_land_retail     NUMBER NOT NULL,
  cost_land            NUMBER NOT NULL,
  cost_cc_resi         NUMBER NOT NULL,
  cost_cc_retail       NUMBER NOT NULL,
  cost_construction    NUMBER NOT NULL,
  cost_soft_resi       NUMBER NOT NULL,
  cost_soft_retail     NUMBER NOT NULL,
  cost_soft            NUMBER NOT NULL,
  cost_stat_resi       NUMBER NOT NULL,
  cost_stat_retail     NUMBER NOT NULL,
  cost_statutory       NUMBER NOT NULL,
  cost_cont_resi       NUMBER NOT NULL,
  cost_cont_retail     NUMBER NOT NULL,
  cost_contingency     NUMBER NOT NULL,
  cost_dev_resi        NUMBER NOT NULL,
  cost_dev_retail      NUMBER NOT NULL,
  cost_dev_mgmt        NUMBER NOT NULL,
  cost_cof_resi        NUMBER NOT NULL,
  cost_cof_retail      NUMBER NOT NULL,
  cost_cof             NUMBER NOT NULL,
  cost_se_resi         NUMBER NOT NULL,
  cost_se_retail       NUMBER NOT NULL,
  cost_sales_expense   NUMBER NOT NULL,
  cost_mk_resi         NUMBER NOT NULL,
  cost_mk_retail       NUMBER NOT NULL,
  cost_marketing       NUMBER NOT NULL,
  cost_resi            NUMBER NOT NULL,
  cost_retail          NUMBER NOT NULL,
  cost_total           NUMBER NOT NULL,
  profit_np_resi       NUMBER NOT NULL,
  profit_np_retail     NUMBER NOT NULL,
  profit_net_profit    NUMBER NOT NULL,
  profit_margin_resi   NUMBER NOT NULL,
  profit_margin_retail NUMBER NOT NULL,
  profit_margin_pct    NUMBER NOT NULL,
  kpi_total_revenue    NUMBER NOT NULL,
  kpi_total_cost       NUMBER NOT NULL,
  kpi_net_profit       NUMBER NOT NULL,
  kpi_margin_pct       NUMBER NOT NULL,
  kpi_total_units      NUMBER NOT NULL
);

CREATE INDEX idx_feasibility_reporting_archive_project
  ON feasibility_reporting_archive (project_id, version DESC);

CREATE TABLE feasibility_reporting_archive_partners (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  archive_id    NUMBER NOT NULL REFERENCES feasibility_reporting_archive(archive_id) ON DELETE CASCADE,
  partner_order NUMBER NOT NULL,
  partner_name  VARCHAR2(255 CHAR) NOT NULL,
  share_pct     NUMBER NOT NULL,
  profit_share  NUMBER NOT NULL
);

CREATE INDEX idx_feasibility_reporting_archive_partners_archive
  ON feasibility_reporting_archive_partners (archive_id, partner_order);
