-- =============================================================
-- Commercial Team Cost Tracking Schema - Oracle
-- Tracks actual commitments and projections per project/month
-- =============================================================

CREATE TABLE cost_categories (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  code          VARCHAR2(100 CHAR) NOT NULL UNIQUE,
  name          VARCHAR2(255 CHAR) NOT NULL,
  description   VARCHAR2(1000 CHAR),
  display_order NUMBER DEFAULT 0 NOT NULL,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

MERGE INTO cost_categories tgt
USING (
  SELECT 'hard' AS code, 'Hard Cost' AS name, 'Construction, materials, labor, and direct project costs' AS description, 1 AS display_order FROM dual
  UNION ALL
  SELECT 'professional_fees', 'Professional Fees', 'Design, engineering, permits, and indirect professional fees', 2 FROM dual
  UNION ALL
  SELECT 'authority', 'Authority Fees', 'Government fees, municipality charges, and regulatory costs', 3 FROM dual
) src
ON (tgt.code = src.code)
WHEN NOT MATCHED THEN
  INSERT (code, name, description, display_order)
  VALUES (src.code, src.name, src.description, src.display_order);

CREATE TABLE project_monthly_costs (
  id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  project_id       NUMBER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  category_id      NUMBER NOT NULL REFERENCES cost_categories(id) ON DELETE CASCADE,
  year             NUMBER NOT NULL,
  month            NUMBER NOT NULL CHECK (month BETWEEN 1 AND 12),
  actual_amount    NUMBER(15,2),
  projected_amount NUMBER(15,2),
  notes            CLOB,
  created_by       VARCHAR2(255 CHAR),
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_project_monthly_costs UNIQUE (project_id, category_id, year, month)
);

CREATE INDEX idx_monthly_costs_project_year_month
  ON project_monthly_costs (project_id, year, month);

CREATE INDEX idx_monthly_costs_category
  ON project_monthly_costs (category_id);
