-- =============================================================
-- Cost Tracking V2 - Team segregation, Revenue, Budget
-- =============================================================

ALTER TABLE cost_categories
  ADD (team VARCHAR2(30 CHAR) DEFAULT 'commercial' NOT NULL);

UPDATE cost_categories
SET
  code = 'professional_fees',
  name = 'Professional Fees',
  description = 'Design, engineering, permits, and indirect professional fees'
WHERE code = 'soft'
  AND NOT EXISTS (
    SELECT 1 FROM cost_categories existing WHERE existing.code = 'professional_fees'
  );

UPDATE cost_categories
SET team = 'commercial'
WHERE code IN ('hard', 'professional_fees', 'authority');

MERGE INTO cost_categories tgt
USING (
  SELECT 'contingency' AS code, 'Contingency' AS name, 'Project contingency reserves' AS description, 4 AS display_order, 'commercial' AS team FROM dual
  UNION ALL
  SELECT 'sales_expenses', 'Sales Expenses', 'Sales commissions and related expenses', 5, 'sales' FROM dual
  UNION ALL
  SELECT 'marketing', 'Marketing', 'Marketing campaigns, events, and brand costs', 6, 'marketing' FROM dual
) src
ON (tgt.code = src.code)
WHEN MATCHED THEN
  UPDATE SET
    tgt.name = src.name,
    tgt.description = src.description,
    tgt.display_order = src.display_order,
    tgt.team = src.team
WHEN NOT MATCHED THEN
  INSERT (code, name, description, display_order, team)
  VALUES (src.code, src.name, src.description, src.display_order, src.team);

ALTER TABLE project_monthly_costs
  ADD (budget_amount NUMBER(15,2));

CREATE TABLE project_monthly_revenue (
  id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  project_id       NUMBER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  year             NUMBER NOT NULL,
  month            NUMBER NOT NULL CHECK (month BETWEEN 1 AND 12),
  budget_amount    NUMBER(15,2),
  actual_amount    NUMBER(15,2),
  projected_amount NUMBER(15,2),
  notes            CLOB,
  created_by       VARCHAR2(255 CHAR),
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_project_monthly_revenue UNIQUE (project_id, year, month)
);

CREATE INDEX idx_monthly_revenue_project_year
  ON project_monthly_revenue (project_id, year, month);

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW project_cost_summary';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW project_cost_annual_summary';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE OR REPLACE VIEW project_cost_summary AS
SELECT
  pmc.project_id,
  p.name AS project_name,
  pmc.year,
  pmc.month,
  SUM(pmc.actual_amount) AS total_actual,
  SUM(CASE WHEN pmc.projected_amount IS NOT NULL THEN pmc.projected_amount END) AS total_projected,
  SUM(CASE WHEN pmc.budget_amount IS NOT NULL THEN pmc.budget_amount END) AS total_budget,
  SUM(COALESCE(pmc.actual_amount, pmc.projected_amount, 0)) AS blended_total,
  COUNT(pmc.actual_amount) AS categories_with_actual,
  COUNT(*) AS total_categories
FROM project_monthly_costs pmc
JOIN projects p ON p.id = pmc.project_id
GROUP BY pmc.project_id, p.name, pmc.year, pmc.month;

CREATE OR REPLACE VIEW project_cost_annual_summary AS
SELECT
  pmc.project_id,
  p.name AS project_name,
  pmc.year,
  cc.code AS category_code,
  cc.name AS category_name,
  cc.team AS category_team,
  SUM(pmc.actual_amount) AS annual_actual,
  SUM(CASE WHEN pmc.projected_amount IS NOT NULL THEN pmc.projected_amount END) AS annual_projected,
  SUM(CASE WHEN pmc.budget_amount IS NOT NULL THEN pmc.budget_amount END) AS annual_budget,
  SUM(COALESCE(pmc.actual_amount, 0)) AS ytd_actual,
  SUM(
    CASE
      WHEN pmc.month <= EXTRACT(MONTH FROM CURRENT_DATE) AND pmc.projected_amount IS NOT NULL
      THEN pmc.projected_amount
      ELSE 0
    END
  ) AS ytd_projected,
  SUM(CASE WHEN pmc.actual_amount IS NOT NULL THEN 1 ELSE 0 END) AS months_with_actual
FROM project_monthly_costs pmc
JOIN projects p ON p.id = pmc.project_id
JOIN cost_categories cc ON cc.id = pmc.category_id
GROUP BY pmc.project_id, p.name, pmc.year, cc.code, cc.name, cc.team;
