-- =============================================================
-- Separate collections forecast module
-- =============================================================

CREATE TABLE project_collections_installments (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  project_id         NUMBER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  customer_name      VARCHAR2(255 CHAR) DEFAULT ' ' NOT NULL,
  unit_ref           VARCHAR2(255 CHAR) DEFAULT ' ' NOT NULL,
  installment_label  VARCHAR2(255 CHAR) NOT NULL,
  due_date           DATE NOT NULL,
  forecast_amount    NUMBER(15,2) DEFAULT 0 NOT NULL,
  collected_amount   NUMBER(15,2) DEFAULT 0 NOT NULL,
  collection_date    DATE,
  status             VARCHAR2(30 CHAR) DEFAULT 'forecast' NOT NULL
                     CHECK (status IN ('forecast', 'partially_collected', 'collected', 'overdue')),
  probability_pct    NUMBER(5,2) DEFAULT 100 NOT NULL,
  notes              CLOB,
  created_by         VARCHAR2(255 CHAR),
  created_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_project_collections_installments UNIQUE (project_id, unit_ref, installment_label, due_date)
);

CREATE INDEX idx_project_collections_installments_project_due
  ON project_collections_installments (project_id, due_date);

CREATE INDEX idx_project_collections_installments_project_status
  ON project_collections_installments (project_id, status);
