CREATE TABLE collections_completion_lookup (
  id                            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  building_name                 VARCHAR2(255 CHAR) NOT NULL UNIQUE,
  project_dld_completion_date   DATE,
  latest_construction_progress  NUMBER(7,4),
  created_at                    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at                    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE collections_aging_lookup (
  id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  location_code       VARCHAR2(255 CHAR) NOT NULL UNIQUE,
  bucket_0_29         NUMBER(15,2) DEFAULT 0 NOT NULL,
  bucket_30_59        NUMBER(15,2) DEFAULT 0 NOT NULL,
  bucket_60_89        NUMBER(15,2) DEFAULT 0 NOT NULL,
  bucket_90_179       NUMBER(15,2) DEFAULT 0 NOT NULL,
  bucket_180_365      NUMBER(15,2) DEFAULT 0 NOT NULL,
  bucket_365_plus     NUMBER(15,2) DEFAULT 0 NOT NULL,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
