-- =============================================================
-- Relational feasibility persistence for Oracle migration readiness
-- =============================================================

CREATE TABLE IF NOT EXISTS feasibility_run_inputs (
  run_id              BIGINT PRIMARY KEY REFERENCES feasibility_runs(id) ON DELETE CASCADE,
  project_name        TEXT NOT NULL,
  land_area           NUMERIC,
  land_cost           NUMERIC,
  land_psf            NUMERIC,
  gfa                 NUMERIC,
  nsa_resi            NUMERIC,
  nsa_retail          NUMERIC,
  bua_resi            NUMERIC,
  bua_retail          NUMERIC,
  units_resi          NUMERIC,
  units_retail        NUMERIC,
  resi_psf            NUMERIC,
  retail_psf          NUMERIC,
  car_park_income     NUMERIC,
  cof_on_sales_pct    NUMERIC,
  cc_psf              NUMERIC,
  soft_pct            NUMERIC,
  stat_pct            NUMERIC,
  cont_pct            NUMERIC,
  dev_mgmt_pct        NUMERIC,
  cof_pct             NUMERIC,
  sales_exp_pct       NUMERIC,
  mkt_pct             NUMERIC
);

CREATE TABLE IF NOT EXISTS feasibility_run_metrics (
  run_id                    BIGINT PRIMARY KEY REFERENCES feasibility_runs(id) ON DELETE CASCADE,
  area_land_area            NUMERIC NOT NULL,
  area_gfa                  NUMERIC NOT NULL,
  area_nsa_resi             NUMERIC NOT NULL,
  area_nsa_retail           NUMERIC NOT NULL,
  area_nsa_total            NUMERIC NOT NULL,
  area_bua_resi             NUMERIC NOT NULL,
  area_bua_retail           NUMERIC NOT NULL,
  area_bua_total            NUMERIC NOT NULL,
  area_units_resi           NUMERIC NOT NULL,
  area_units_retail         NUMERIC NOT NULL,
  area_units_total          NUMERIC NOT NULL,
  area_efficiency_pct       NUMERIC NOT NULL,
  revenue_gross_resi        NUMERIC NOT NULL,
  revenue_cof_on_sales      NUMERIC NOT NULL,
  revenue_net_resi          NUMERIC NOT NULL,
  revenue_retail            NUMERIC NOT NULL,
  revenue_car_park_income   NUMERIC NOT NULL,
  revenue_total_inflows     NUMERIC NOT NULL,
  revenue_resi              NUMERIC NOT NULL,
  revenue_total             NUMERIC NOT NULL,
  cost_land_resi            NUMERIC NOT NULL,
  cost_land_retail          NUMERIC NOT NULL,
  cost_land                 NUMERIC NOT NULL,
  cost_cc_resi              NUMERIC NOT NULL,
  cost_cc_retail            NUMERIC NOT NULL,
  cost_construction         NUMERIC NOT NULL,
  cost_soft_resi            NUMERIC NOT NULL,
  cost_soft_retail          NUMERIC NOT NULL,
  cost_soft                 NUMERIC NOT NULL,
  cost_stat_resi            NUMERIC NOT NULL,
  cost_stat_retail          NUMERIC NOT NULL,
  cost_statutory            NUMERIC NOT NULL,
  cost_cont_resi            NUMERIC NOT NULL,
  cost_cont_retail          NUMERIC NOT NULL,
  cost_contingency          NUMERIC NOT NULL,
  cost_dev_resi             NUMERIC NOT NULL,
  cost_dev_retail           NUMERIC NOT NULL,
  cost_dev_mgmt             NUMERIC NOT NULL,
  cost_cof_resi             NUMERIC NOT NULL,
  cost_cof_retail           NUMERIC NOT NULL,
  cost_cof                  NUMERIC NOT NULL,
  cost_se_resi              NUMERIC NOT NULL,
  cost_se_retail            NUMERIC NOT NULL,
  cost_sales_expense        NUMERIC NOT NULL,
  cost_mk_resi              NUMERIC NOT NULL,
  cost_mk_retail            NUMERIC NOT NULL,
  cost_marketing            NUMERIC NOT NULL,
  cost_resi                 NUMERIC NOT NULL,
  cost_retail               NUMERIC NOT NULL,
  cost_total                NUMERIC NOT NULL,
  profit_np_resi            NUMERIC NOT NULL,
  profit_np_retail          NUMERIC NOT NULL,
  profit_net_profit         NUMERIC NOT NULL,
  profit_margin_resi        NUMERIC NOT NULL,
  profit_margin_retail      NUMERIC NOT NULL,
  profit_margin_pct         NUMERIC NOT NULL,
  profit_cash_profit        NUMERIC NOT NULL,
  profit_cash_margin_pct    NUMERIC NOT NULL,
  kpi_total_revenue         NUMERIC NOT NULL,
  kpi_total_cost            NUMERIC NOT NULL,
  kpi_net_profit            NUMERIC NOT NULL,
  kpi_margin_pct            NUMERIC NOT NULL,
  kpi_total_units           NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS feasibility_run_partners (
  id                  BIGSERIAL PRIMARY KEY,
  run_id              BIGINT NOT NULL REFERENCES feasibility_runs(id) ON DELETE CASCADE,
  partner_order       INT NOT NULL,
  partner_name        TEXT NOT NULL,
  share_pct           NUMERIC,
  profit_share        NUMERIC NOT NULL,
  UNIQUE (run_id, partner_order)
);

CREATE INDEX IF NOT EXISTS idx_feasibility_run_partners_run
  ON feasibility_run_partners (run_id, partner_order);

CREATE TABLE IF NOT EXISTS feasibility_archive_inputs (
  archive_id           BIGINT PRIMARY KEY REFERENCES feasibility_archive(id) ON DELETE CASCADE,
  original_run_id      BIGINT NOT NULL,
  project_name         TEXT NOT NULL,
  land_area            NUMERIC,
  land_cost            NUMERIC,
  land_psf             NUMERIC,
  gfa                  NUMERIC,
  nsa_resi             NUMERIC,
  nsa_retail           NUMERIC,
  bua_resi             NUMERIC,
  bua_retail           NUMERIC,
  units_resi           NUMERIC,
  units_retail         NUMERIC,
  resi_psf             NUMERIC,
  retail_psf           NUMERIC,
  car_park_income      NUMERIC,
  cof_on_sales_pct     NUMERIC,
  cc_psf               NUMERIC,
  soft_pct             NUMERIC,
  stat_pct             NUMERIC,
  cont_pct             NUMERIC,
  dev_mgmt_pct         NUMERIC,
  cof_pct              NUMERIC,
  sales_exp_pct        NUMERIC,
  mkt_pct              NUMERIC
);

CREATE TABLE IF NOT EXISTS feasibility_archive_metrics (
  archive_id                 BIGINT PRIMARY KEY REFERENCES feasibility_archive(id) ON DELETE CASCADE,
  area_land_area             NUMERIC NOT NULL,
  area_gfa                   NUMERIC NOT NULL,
  area_nsa_resi              NUMERIC NOT NULL,
  area_nsa_retail            NUMERIC NOT NULL,
  area_nsa_total             NUMERIC NOT NULL,
  area_bua_resi              NUMERIC NOT NULL,
  area_bua_retail            NUMERIC NOT NULL,
  area_bua_total             NUMERIC NOT NULL,
  area_units_resi            NUMERIC NOT NULL,
  area_units_retail          NUMERIC NOT NULL,
  area_units_total           NUMERIC NOT NULL,
  area_efficiency_pct        NUMERIC NOT NULL,
  revenue_gross_resi         NUMERIC NOT NULL,
  revenue_cof_on_sales       NUMERIC NOT NULL,
  revenue_net_resi           NUMERIC NOT NULL,
  revenue_retail             NUMERIC NOT NULL,
  revenue_car_park_income    NUMERIC NOT NULL,
  revenue_total_inflows      NUMERIC NOT NULL,
  revenue_resi               NUMERIC NOT NULL,
  revenue_total              NUMERIC NOT NULL,
  cost_land_resi             NUMERIC NOT NULL,
  cost_land_retail           NUMERIC NOT NULL,
  cost_land                  NUMERIC NOT NULL,
  cost_cc_resi               NUMERIC NOT NULL,
  cost_cc_retail             NUMERIC NOT NULL,
  cost_construction          NUMERIC NOT NULL,
  cost_soft_resi             NUMERIC NOT NULL,
  cost_soft_retail           NUMERIC NOT NULL,
  cost_soft                  NUMERIC NOT NULL,
  cost_stat_resi             NUMERIC NOT NULL,
  cost_stat_retail           NUMERIC NOT NULL,
  cost_statutory             NUMERIC NOT NULL,
  cost_cont_resi             NUMERIC NOT NULL,
  cost_cont_retail           NUMERIC NOT NULL,
  cost_contingency           NUMERIC NOT NULL,
  cost_dev_resi              NUMERIC NOT NULL,
  cost_dev_retail            NUMERIC NOT NULL,
  cost_dev_mgmt              NUMERIC NOT NULL,
  cost_cof_resi              NUMERIC NOT NULL,
  cost_cof_retail            NUMERIC NOT NULL,
  cost_cof                   NUMERIC NOT NULL,
  cost_se_resi               NUMERIC NOT NULL,
  cost_se_retail             NUMERIC NOT NULL,
  cost_sales_expense         NUMERIC NOT NULL,
  cost_mk_resi               NUMERIC NOT NULL,
  cost_mk_retail             NUMERIC NOT NULL,
  cost_marketing             NUMERIC NOT NULL,
  cost_resi                  NUMERIC NOT NULL,
  cost_retail                NUMERIC NOT NULL,
  cost_total                 NUMERIC NOT NULL,
  profit_np_resi             NUMERIC NOT NULL,
  profit_np_retail           NUMERIC NOT NULL,
  profit_net_profit          NUMERIC NOT NULL,
  profit_margin_resi         NUMERIC NOT NULL,
  profit_margin_retail       NUMERIC NOT NULL,
  profit_margin_pct          NUMERIC NOT NULL,
  profit_cash_profit         NUMERIC NOT NULL,
  profit_cash_margin_pct     NUMERIC NOT NULL,
  kpi_total_revenue          NUMERIC NOT NULL,
  kpi_total_cost             NUMERIC NOT NULL,
  kpi_net_profit             NUMERIC NOT NULL,
  kpi_margin_pct             NUMERIC NOT NULL,
  kpi_total_units            NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS feasibility_archive_partners (
  id                  BIGSERIAL PRIMARY KEY,
  archive_id          BIGINT NOT NULL REFERENCES feasibility_archive(id) ON DELETE CASCADE,
  partner_order       INT NOT NULL,
  partner_name        TEXT NOT NULL,
  share_pct           NUMERIC,
  profit_share        NUMERIC NOT NULL,
  UNIQUE (archive_id, partner_order)
);

CREATE INDEX IF NOT EXISTS idx_feasibility_archive_partners_archive
  ON feasibility_archive_partners (archive_id, partner_order);
